### ISSUE TITLE
license is not matched project and `package.json`

### ISSUE THREAD

**Issue by HyunmoAhn** [bbvch13531/prefeel-lib#3]
I know `prefeel-lib` project is [GPLv3](https://github.com/bbvch13531/prefeel-lib/blob/master/LICENSE).
 But I found that License is writed `MIT` License in [prefeel-lib_frontend/package.json](https://github.com/bbvch13531/prefeel-lib/blob/master/prefeel-lib_frontend/package.json#L59) and [prefeel-lib_backend/package.json](https://github.com/bbvch13531/prefeel-lib/blob/master/prefeel-lib_backend/package.json#L6).

I wonder if it was intended? if not, how about edit License in package.json?

**Comment by bbvch13531** [comment]
Thanks for your report. I'll check and update it.
